name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    uses: zuspec/zuspec-release/.github/workflows/zuspec-pybuild.yml@main
    with:
      version_dir: 'src/zuspec/be/trace'
      build_universal: true
      build_linux: false
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
